CREATE TABLE users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(100) NOT NULL,
    username VARCHAR(100) NOT NULL,
    password VARCHAR(64) NOT NULL,
    correo VARCHAR(100),
    admin TINYINT(1),
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE modelos (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(100) NOT NULL,
    tarifa_por_minuto VARCHAR(20),
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE promociones (
    id INT PRIMARY KEY AUTO_INCREMENT,
    codigo VARCHAR(100) NOT NULL,
    descuento DECIMAL(5,2) NOT NULL,
    fecha_expiracion TIMESTAMP NULL,
    estado TINYINT(1),
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE estaciones (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(100) NOT NULL,
    direccion VARCHAR(200),
    capacidad INT,
    latitud DECIMAL(10, 8),
    longitud DECIMAL(11, 8),
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE metodo_de_pagos (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    alias VARCHAR(100) NOT NULL,
    tipo VARCHAR(50) NOT NULL,
    titular VARCHAR(100) NOT NULL,
    numero VARCHAR(20) NOT NULL,
    fecha_expiracion VARCHAR(10) NOT NULL,
    cvv VARCHAR(5) NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB;

CREATE TABLE vehiculos (
    id INT PRIMARY KEY AUTO_INCREMENT,
    modelo_id INT NOT NULL,
    no_serie VARCHAR(100) NOT NULL,
    estado TINYINT(1),
    estacion_id INT,
    latitud DECIMAL(10, 8),
    longitud DECIMAL(11, 8),
    bateria INT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (modelo_id) REFERENCES modelos(id),
    FOREIGN KEY (estacion_id) REFERENCES estaciones(id)
) ENGINE=InnoDB;

CREATE TABLE viajes (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    vehiculo_id INT NOT NULL,
    estacion_destino_id INT,
    hora_inicio TIMESTAMP NULL,
    hora_fin TIMESTAMP NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (vehiculo_id) REFERENCES vehiculos(id),
    FOREIGN KEY (estacion_destino_id) REFERENCES estaciones(id)
) ENGINE=InnoDB;

CREATE TABLE transacciones (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    viaje_id INT NOT NULL,
    metodo_de_pago_id INT NOT NULL,
    costo DECIMAL(10, 2),
    promocion_id INT,
    fecha TIMESTAMP NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (viaje_id) REFERENCES viajes(id),
    FOREIGN KEY (metodo_de_pago_id) REFERENCES metodo_de_pagos(id),
    FOREIGN KEY (promocion_id) REFERENCES promociones(id)
) ENGINE=InnoDB;